### ISSUE TITLE
Content type text/plain not supported

### ISSUE THREAD

**Issue by jstorm31** [jiawei397/deno_es#1]
I have a problem with inserting a document to the Elastic Search index. I'm running Elastic version `7.14.1`.

Creating the document:
```ts
const info = await client.create({
        index: INDEX_KEY,
        id,
        body: {
            name: index.video.name,
            topics: index.index,
        }
})
```

And get the following error:
```
{"error":"Content-Type header [text/plain;charset=UTF-8] is not supported","status":406}
HTTP error, status = 406, statusText = Not Acceptable
```

It seems like the `Content-Type` for version `7.14.x` should be `application/json`. What version of Elastic does this lib support?

**Comment by jiawei397** [comment]
First of all, I'm glad to have friends using the code and this 
I am so sorry that I dit not make unit. It is a bug which caused by I changed my base fetch package. I removed the default content-type when method is put.
Now I fixed it, but sadly cannot publish to deno.land because meeting this:
```
{"success":false,"error":"provided sub directory is not valid as it does not end with a /"}
```

It seems the deno.land changed the rule, so I will wait for one day to see the land whether back it.

**Comment by jiawei397** [comment]
I donnot get any answer and it seems that all my projects can't be released, I am waiting for my email which sended to deploy@deno.com.

So my friend, you can use it temporarily:

```ts
import { Client } from "https://raw.githubusercontent.com/jiawei397/deno_es/v0.1.0/mod.ts";
```

**Comment by jiawei397** [comment]
I find the reason why I cannot publish.

My dear friend, you can use now:
```ts
import { Client } from "https://deno.land/x/deno_es@v0.1.0/mod.ts";
```
